// Array of Indian Gods and Goddesses
export const gods = [
    "Brahma",
    "Vishnu",
    "Shiva",
    "Lakshmi",
    "Saraswati",
    "Parvati",
    "Durga",
    "Kali",
    "Ganesha",
    "Kartikeya",
    "Hanuman",
    "Indra",
    "Agni",
    "Varuna",
    "Vayu",
    "Surya",
    "Chandra",
    "Yama",
    "Kubera",
    "Kamadeva",
    "Dhanvantari",
    "Ayyappa",
    "Narada",
    "Nandi",
    "Shani",
    "Rama",
    "Krishna",
    "Radha",
    "Balarama",
    "Sita",
    "Lakshmana",
    "Bharata",
    "Shatrughna",
    "Garuda",
    "Vishwakarma",
    "Bhumi Devi",
    "Annapurna",
    "Gayatri",
    "Ashwini Kumars",
    "Savitr",
    "Prithvi",
    "Aranyani",
    "Manasa",
    "Tulsi",
    "Rati",
    "Santoshi Mata",
    "Meenakshi",
    "Chamunda",
    "Bhuvaneshwari",
    "Tripura Sundari",
];

// Array of vivid colors
export const vividColors = [
    "crimson red",
    "royal blue",
    "emerald green",
    "sunset orange",
    "deep purple",
    "golden yellow",
    "turquoise",
    "magenta",
    "maroon",
    "saffron",
    "ruby red",
    "electric blue",
    "forest green",
    "amber",
    "plum purple",
    "cobalt blue",
    "fuchsia pink",
    "burnt orange",
    "lime green",
    "bright cyan",
    "scarlet",
    "navy blue",
    "chartreuse",
    "violet",
    "bronze",
    "topaz yellow",
    "indigo",
    "flame red",
    "aqua teal",
    "hot pink",
    "raspberry",
    "tangerine",
    "midnight blue",
    "jade green",
    "carmine",
    "canary yellow",
    "lapis lazuli",
    "mulberry",
    "vermillion",
    "zesty lime",
    "poppy red",
    "periwinkle blue",
    "mandarin orange",
    "blush coral",
    "royal purple",
    "citrine gold",
    "celestial blue",
    "peacock green",
    "candy apple red",
    "neon violet",
];

// Array of delicate color garments
export const softColors = [
    "pastel pink",
    "ivory white",
    "sky blue",
    "lavender",
    "peach",
    "mint green",
    "cream",
    "light beige",
    "dusty rose",
    "soft lilac",
    "powder blue",
    "baby yellow",
    "mauve",
    "pale peach",
    "frosted mint",
    "blush pink",
    "light coral",
    "eggshell",
    "misty grey",
    "honeydew",
    "pastel violet",
    "soft teal",
    "light blush",
    "pale lavender",
    "cloud white",
    "pale turquoise",
    "cotton candy pink",
    "moonlight grey",
    "beige cream",
    "pale mauve",
    "porcelain white",
    "satin peach",
    "light rose",
    "faint aqua",
    "gentle lilac",
    "silky almond",
    "vanilla cream",
    "dusty peach",
    "snow blue",
    "milky white",
    "pale sky",
    "baby blue",
    "pastel green",
    "soft sand",
    "pearl white",
    "subtle pink",
    "fog grey",
    "soft gold",
    "linen cream",
    "rose quartz",
];

// Array of props
export const props = [
    "lotus flower",
    "trident",
    "mace",
    "scripture scroll",
    "conch shell",
    "flute",
    "bow and arrow",
    "lamp",
    "beaded necklace",
    "shield",
    "chakra disc",
    "sword",
    "staff",
    "veena",
    "bell",
    "water pot",
    "crown",
    "gemstone",
    "mirror",
    "torch",
    "drum (damaru)",
    "rope noose",
    "axe",
    "book",
    "garland",
    "rosary (japa mala)",
    "snake coil",
    "umbrella",
    "flag",
    "vessel of gold",
    "fireball",
    "palm leaf manuscript",
    "gold coin pot",
    "holy thread",
    "feather fan",
    "stick of incense",
    "scales of justice",
    "small statue",
    "swan feather",
    "flower bouquet",
    "tree branch",
    "moon crescent",
    "sun orb",
    "consecrated water bowl",
    "elephant goad",
    "tiger skin cloth",
    "scorpion emblem",
    "mountain rock",
    "crystal bead",
    "fruit basket",
    "diamond jewel",
];

// Array of cozy settings
export const settings = [
    "handwoven rug by a fireplace",
    "sunlit wooden shelf with books",
    "knitted blanket on a rocking chair",
    "quiet meditation corner",
    "temple-inspired room with incense",
    "window seat with flowing curtains",
    "rustic wooden desk with candles",
    "wicker basket on a wooden floor",
    "colorful cushion-filled reading nook",
    "vintage shelf with spiritual ornaments",
    "bamboo mat under soft lighting",
    "low wooden table with brass bowls",
    "open veranda with swaying plants",
    "marble floor with diya lamps",
    "sunbeam-filled prayer alcove",
    "embroidered floor cushions near incense",
    "cozy swing chair with knitted covers",
    "traditional Indian charpai with throw pillows",
    "floor mat near an oil lamp",
    "terracotta pot beside a sacred plant",
    "dimly lit altar with bells",
    "clay walls with rangoli art",
    "window nook with woolen drapes",
    "small temple shelf with idols and candles",
    "open courtyard with tulsi plant",
    "earth-toned room with carved pillars",
    "shaded garden with stone bench",
    "wood-paneled room with prayer beads",
    "brass tray beside a Ganga Jal pot",
    "hand-painted wall near a lamp",
    "jute carpet under golden lighting",
    "room corner with dreamcatchers and incense smoke",
    "soft prayer rug with folded hands pose",
    "wooden mandir glowing with diyas",
    "cozy low bed with deity paintings",
    "book-filled wall with a soft chair",
    "light-filled room with lattice windows",
    "woolen shawl draped on a bench",
    "reed mat with fresh flowers and sweets",
    "warm room with cow bells and bells",
    "sunrise glow through a cotton curtain",
    "earthy floor with garland offerings",
    "floral-printed blanket over a rocking stool",
    "granite step near a diya lamp",
    "modest hut room with divine posters",
    "cane stool beside a copper kalash",
    "deity corner with fresh marigolds",
    "painted clay pots lined against a wall",
    "sacred space lit by moonlight",
    "woven basket with wool and holy threads",
    "home temple corner glowing softly",
];
